# Generated by Django 3.1.7 on 2021-04-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20210402_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='instrument_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='library_selection',
            field=models.CharField(choices=[('RANDOM', 'RANDOM'), ('PCR', 'PCR'), ('RANDOM PCR', 'RANDOM PCR'), ('RT-PCR', 'RT-PCR'), ('HMPR', 'HMPR'), ('MF', 'MF'), ('CF-S', 'CF-S'), ('CF-M', 'CF-M'), ('CF-H', 'CF-H'), ('CF-T', 'CF-T'), ('MDA', 'MDA'), ('MSLL', 'MSLL'), ('cDNA', 'cDNA'), ('ChIP', 'ChIP'), ('MNase', 'MNase'), ('DNAse', 'DNAse'), ('Hybrid Selection', 'Hybrid Selection'), ('Reduced Representation', 'Reduced Representation'), ('Restriction Digest', 'Restriction Digest'), ('5-methylcytidine antibody', '5-methylcytidine antibody'), ('MBD2 protein methyl-CpG binding domain', 'MBD2 protein methyl-CpG binding domain'), ('CAGE', 'CAGE'), ('RACE', 'RACE'), ('size fractionation', 'size fractionation'), ('Padlock probes capture method', 'Padlock probes capture method'), ('other', 'other'), ('unspecified', 'unspecified'), ('cDNA_oligo_dT', 'cDNA_oligo_dT'), ('cDNA_randomPriming', 'cDNA_randomPriming'), ('Inverse rRNA', 'Inverse rRNA'), ('Oligo-dT', 'Oligo-dT'), ('PolyA', 'PolyA'), ('repeat fractionation', 'repeat fractionation')], max_length=100),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='library_source',
            field=models.CharField(choices=[('GENOMIC', 'GENOMIC'), ('TRANSCRIPTOMIC', 'TRANSCRIPTOMIC'), ('METAGENOMIC', 'METAGENOMIC'), ('METATRANSCRIPTOMIC', 'METATRANSCRIPTOMIC'), ('SYNTHETIC', 'SYNTHETIC'), ('VIRAL RNA', 'VIRAL RNA'), ('GENOMIC SINGLE CELL', 'GENOMIC SINGLE CELL'), ('TRANSCRIPTOMIC SINGLE CELL', 'TRANSCRIPTOMIC SINGLE CELL'), ('OTHER', 'OTHER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='library_strategy',
            field=models.CharField(choices=[('WGA', 'WGA'), ('WGS', 'WGS'), ('WXS', 'WXS'), ('RNA-Seq', 'RNA-Seq'), ('miRNA-Seq', 'miRNA-Seq'), ('WCS', 'WCS'), ('CLONE', 'CLONE'), ('POOLCLONE', 'POOLCLONE'), ('AMPLICON', 'AMPLICON'), ('CLONEEND', 'CLONEEND'), ('FINISHING', 'FINISHING'), ('ChIP-Seq', 'ChIP-Seq'), ('MNase-Seq', 'MNase-Seq'), ('DNase-Hypersensitivity', 'DNase-Hypersensitivity'), ('Bisulfite-Seq', 'Bisulfite-Seq'), ('Tn-Seq', 'Tn-Seq'), ('EST', 'EST'), ('FL-cDNA', 'FL-cDNA'), ('CTS', 'CTS'), ('MRE-Seq', 'MRE-Seq'), ('MeDIP-Seq', 'MeDIP-Seq'), ('MBD-Seq', 'MBD-Seq'), ('Synthetic-Long-Read', 'Synthetic-Long-Read'), ('ATAC-seq', 'ATAC-seq'), ('ChIA-PET', 'ChIA-PET'), ('FAIRE-seq', 'FAIRE-seq'), ('Hi-C', 'Hi-C'), ('ncRNA-Seq', 'ncRNA-Seq'), ('RAD-Seq', 'RAD-Seq'), ('RIP-Seq', 'RIP-Seq'), ('SELEX', 'SELEX'), ('ssRNA-seq', 'ssRNA-seq'), ('Targeted-Capture', 'Targeted-Capture'), ('Tethered Chromatin Conformation Capture', 'Tethered Chromatin Conformation Capture'), ('OTHER', 'OTHER')], max_length=100),
        ),
    ]
